image: golang:latest

before_script:
  - go-wrapper download

test:
  dependencies: []
  script:
    - go test -v ./...

build:win64:
  stage: build
  variables:
    GOOS: windows
    GOARCH: amd64
  script:
    - go build -o rpgmaker-patch-translator.exe
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
    - rpgmaker-patch-translator.exe

build:linux64:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - go build -o rpgmaker-patch-translator
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
    - rpgmaker-patch-translator

build:osx:
  stage: build
  variables:
    GOOS: darwin
    GOARCH: amd64
  script:
    - go build -o rpgmaker-patch-translator
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
    - rpgmaker-patch-translator
